name: Wildfly s2i Image with custom wildfly-cekit-module
on:
  repository_dispatch:
    types: [custom-wf-cekit-build]
    paths-ignore:
      - 'docs/**'
env:
  LANG: en_US.UTF-8
  S2I_URI: https://api.github.com/repos/openshift/source-to-image/releases/latest
  CEKIT_VERSION: 3.2.1
  QUAY_REPO: ${{ secrets.QUAY_REPO }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  IMAGE_VERSION: wf-cekit-${{ github.event.client_payload.wf-cekit-ref }}
  WFCEKIT_FORK: ${{ github.event.client_payload.wf-cekit-fork }}
  WFCEKIT_BRANCH: ${{ github.event.client_payload.wf-cekit-ref }}
jobs:
  wfci:
    name: Wildfly-s2i Build, Deploy and Test using custom wildfly-cekit-modules
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.client_payload.wf-s2i-ref }}
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check quay.io configuration
        if: env.QUAY_USERNAME == '' || env.QUAY_REPO == ''
        run: |
          echo "quay.io configuration is incomplete, push to quay.io will be skipped. If you wish to push built images to quay.io, please ensure the secrets QUAY_REPO, QUAY_USERNAME and QUAY_PASSWORD are created in the project."
      - name: Verify latest centos image is present
        run: |
          docker image ls | grep centos || true
          docker pull centos:7
          docker pull centos/s2i-base-centos7
          docker image ls | grep centos
      - name: Setup required system packages
        run: |
          sudo apt-get update
          sudo apt-get install krb5-multidev libkrb5-dev
          sudo apt-get install bash
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup virtualenv and install cekit and required packages
        run: |
          python --version
          sudo pip install virtualenv
          mkdir ~/cekit${{ env.CEKIT_VERSION }}
          python3 -m venv ~/cekit${{ env.CEKIT_VERSION }}
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          pip install cekit==${{ env.CEKIT_VERSION }} docker==5.0.3 docker-squash odcs behave lxml 
      - name: install s2i binary
        run: |
          echo ===== Installing s2i from ${{ env.S2I_URL }} =====
          mkdir /tmp/s2i/ && cd /tmp/s2i/
          curl -s ${{ env.S2I_URI }} \
           | grep browser_download_url \
           | grep linux-amd64 \
           | cut -d '"' -f 4 \
           | wget -qi -
           tar xvf source-to-image*.gz
           sudo mv s2i /usr/bin
           which s2i
           s2i version
      - name: Build
        run: |
          pushd tools
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          bash ./build-custom-s2i-wf-cekit-image.sh  ${{ env.IMAGE_VERSION }} ${{ env.WFCEKIT_FORK }} ${{ env.WFCEKIT_BRANCH }}
          popd
          docker image ls
      - name: Push to quay.io
        if: env.QUAY_USERNAME != '' && env.QUAY_REPO != ''
        run: |
            BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${{ env.IMAGE_VERSION }}"
            echo QUAY_REPO: "${{ secrets.QUAY_REPO }}"
            echo Pushing to quay.io with the tag :${{ env.IMAGE_VERSION }}
            echo BUILDER_IMAGE: ${BUILDER_IMAGE}
            docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
            docker tag wildfly/wildfly-centos7:latest ${BUILDER_IMAGE}
            docker push ${BUILDER_IMAGE}
      - name: Behave Tests
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          pushd wildfly-builder-image
          cekit -v test --image=wildfly/wildfly-centos7:latest behave
          popd
      - name: Additional Tests
        run: |
          export IMAGE_VERSION=latest
          export NAMESPACE=wildfly
          export PLATFORM=centos7
          export IMAGE_NAME=${NAMESPACE}/wildfly-${PLATFORM}
          export RUNTIME_IMAGE_NAME=quay.io/${NAMESPACE}/wildfly-runtime-${PLATFORM}
          docker pull ${RUNTIME_IMAGE_NAME}
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          ./test/run